name: ci-cd
on:
  push:
    branches:
      - main
env:
  GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY }}
  GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_AUTH_DOMAIN }}
  GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}
  GATSBY_FIREBASE_STORAGE_BUCKET: ${{ secrets.GATSBY_FIREBASE_STORAGE_BUCKET }}
  GATSBY_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.GATSBY_FIREBASE_MESSAGING_SENDER_ID }}
  GATSBY_FIREBASE_APP_ID: ${{ secrets.GATSBY_FIREBASE_APP_ID }}
  GATSBY_SITE_URL: ${{ secrets.GATSBY_SITE_URL }}
  GATSBY_ALLOWED_DOMAIN: ${{ secrets.GATSBY_ALLOWED_DOMAIN }}
  GATSBY_HELLO_EMAIL: ${{ secrets.GATSBY_HELLO_EMAIL }}
  GATSBY_API_URL: ${{ secrets.GATSBY_API_URL }}
  GATSBY_FIREBASE_ANALYTICS: ${{ secrets.GATSBY_FIREBASE_ANALYTICS }}

jobs:
  pre-build:
    name: Pre build
    runs-on: ubuntu-latest
    env:
      GATSBY_GAUTH: ${{secrets.GATSBY_GAUTH}}
      GATSBY_TEST_USER_EMAIL: ${{secrets.GATSBY_TEST_USER_EMAIL}}
      GATSBY_TEST_USER_PASSWORD: ${{secrets.GATSBY_TEST_USER_PASSWORD}}
      CI_PREVIEW_REF_SLUG: ${{ secrets.CI_PREVIEW_REF_SLUG }}
    steps:
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Pre build
        uses: w9jds/firebase-action@master
        run: node ./prebuild.mjs
      - name: Download dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
  deploy-preview:
    name: Deploy preview
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy preview
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy ${{ secrets.CI_PREVIEW_REF_SLUG }}
  greenframe-analyze:
    name: Greenframe analyze
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - name: Load prebuild.env
        uses: xom9ikk/dotenv@v2
        with:
          path: ./prebuild.env
      - uses: actions/checkout@master
      - run: curl https://assets.greenframe.io/install.sh | bash
      - run: greenframe analyze ${{ secrets.PREVIEW_URL }} ./greenframe-scenario-1.js
      - run: greenframe analyze ${{ secrets.PREVIEW_URL }} ./greenframe-scenario-2.js
      - run: greenframe analyze ${{ secrets.PREVIEW_URL }} ./greenframe-scenario-3.js
      - run: greenframe analyze ${{ secrets.PREVIEW_URL }} ./greenframe-scenario-4.js
      env:
        GREENFRAME_SECRET_TOKEN: ${{ secrets.GREENFRAME_SECRET_TOKEN }}
  stop-preview:
    name: Stop preview
    needs: greenframe-analyze
    runs-on: ubuntu-latest
    steps:
      - name: Stop preview
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:delete -f ${{ secrets.CI_PREVIEW_REF_SLUG }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Download dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ps
