name: ci-cd
on:
  push:
    branches:
      - test-arnaud
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Download dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY }}
          GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_AUTH_DOMAIN }}
          GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}
          GATSBY_FIREBASE_STORAGE_BUCKET: ${{ secrets.GATSBY_FIREBASE_STORAGE_BUCKET }}
          GATSBY_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.GATSBY_FIREBASE_MESSAGING_SENDER_ID }}
          GATSBY_FIREBASE_APP_ID: ${{ secrets.GATSBY_FIREBASE_APP_ID }}
          GATSBY_SITE_URL: ${{ secrets.GATSBY_SITE_URL }}
          GATSBY_ALLOWED_DOMAIN: ${{ secrets.GATSBY_ALLOWED_DOMAIN }}
          GATSBY_HELLO_EMAIL: ${{ secrets.GATSBY_HELLO_EMAIL }}
          GATSBY_API_URL: ${{ secrets.GATSBY_API_URL }}
          GATSBY_FIREBASE_ANALYTICS: ${{ secrets.GATSBY_FIREBASE_ANALYTICS }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ps
